/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AisRouteImport } from './routes/ais'
import { Route as BerthsRouteImport } from './routes/berths'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TidesRouteImport } from './routes/tides'
import { Route as VesselsRouteImport } from './routes/vessels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AisRoute = AisRouteImport.update({
  id: '/ais',
  path: '/ais',
  getParentRoute: () => rootRouteImport,
} as any)
const BerthsRoute = BerthsRouteImport.update({
  id: '/berths',
  path: '/berths',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TidesRoute = TidesRouteImport.update({
  id: '/tides',
  path: '/tides',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsRoute = VesselsRouteImport.update({
  id: '/vessels',
  path: '/vessels',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ais': typeof AisRoute
  '/berths': typeof BerthsRoute
  '/operators': typeof OperatorsRoute
  '/reports': typeof ReportsRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/tides': typeof TidesRoute
  '/vessels': typeof VesselsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ais': typeof AisRoute
  '/berths': typeof BerthsRoute
  '/operators': typeof OperatorsRoute
  '/reports': typeof ReportsRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/tides': typeof TidesRoute
  '/vessels': typeof VesselsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ais': typeof AisRoute
  '/berths': typeof BerthsRoute
  '/operators': typeof OperatorsRoute
  '/reports': typeof ReportsRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/tides': typeof TidesRoute
  '/vessels': typeof VesselsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ais'
    | '/berths'
    | '/operators'
    | '/reports'
    | '/scheduling'
    | '/settings'
    | '/tides'
    | '/vessels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ais'
    | '/berths'
    | '/operators'
    | '/reports'
    | '/scheduling'
    | '/settings'
    | '/tides'
    | '/vessels'
  id:
    | '__root__'
    | '/'
    | '/ais'
    | '/berths'
    | '/operators'
    | '/reports'
    | '/scheduling'
    | '/settings'
    | '/tides'
    | '/vessels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AisRoute: typeof AisRoute
  BerthsRoute: typeof BerthsRoute
  OperatorsRoute: typeof OperatorsRoute
  ReportsRoute: typeof ReportsRoute
  SchedulingRoute: typeof SchedulingRoute
  SettingsRoute: typeof SettingsRoute
  TidesRoute: typeof TidesRoute
  VesselsRoute: typeof VesselsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ais': {
      id: '/ais'
      path: '/ais'
      fullPath: '/ais'
      preLoaderRoute: typeof AisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berths': {
      id: '/berths'
      path: '/berths'
      fullPath: '/berths'
      preLoaderRoute: typeof BerthsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tides': {
      id: '/tides'
      path: '/tides'
      fullPath: '/tides'
      preLoaderRoute: typeof TidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels': {
      id: '/vessels'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AisRoute: AisRoute,
  BerthsRoute: BerthsRoute,
  OperatorsRoute: OperatorsRoute,
  ReportsRoute: ReportsRoute,
  SchedulingRoute: SchedulingRoute,
  SettingsRoute: SettingsRoute,
  TidesRoute: TidesRoute,
  VesselsRoute: VesselsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
